# Generated by Django 3.2.8 on 2021-11-08 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default='', max_length=2048)),
                ('coincapmarket_url', models.URLField(blank=True, default='', max_length=254)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField(blank=True, default='', max_length=254)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=254)),
                ('twitter_url', models.URLField(blank=True, default='', max_length=254)),
                ('github_url', models.URLField(blank=True, default='', max_length=254)),
                ('facebook_url', models.URLField(blank=True, default='', max_length=254)),
                ('discord_url', models.URLField(blank=True, default='', max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verify_token', models.CharField(blank=True, default='', max_length=256)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=4)),
                ('canary_beta_public_key', models.CharField(max_length=64)),
                ('canary_live_public_key', models.CharField(max_length=64)),
                ('canary_test_public_key', models.CharField(max_length=64)),
                ('custom_domain', models.CharField(blank=True, default='', max_length=256)),
                ('created', models.DateTimeField(auto_now=True)),
                ('debug', models.CharField(blank=True, default='INFO', max_length=100)),
                ('domain_svc', models.CharField(blank=True, default='verigasvc.com', max_length=256)),
                ('enable_custom_domain', models.BooleanField(default=False)),
                ('faucet_public_key', models.CharField(max_length=64)),
                ('landing_public_key', models.CharField(max_length=64)),
                ('genesis_beta_public_key', models.CharField(max_length=64)),
                ('genesis_beta_account', models.CharField(max_length=65)),
                ('genesis_beta_work', models.CharField(max_length=16)),
                ('genesis_beta_signature', models.CharField(max_length=128)),
                ('genesis_dev_public_key', models.CharField(max_length=64)),
                ('genesis_dev_private_key', models.CharField(max_length=64)),
                ('genesis_dev_account', models.CharField(max_length=65)),
                ('genesis_dev_work', models.CharField(max_length=16)),
                ('genesis_dev_signature', models.CharField(max_length=128)),
                ('genesis_live_public_key', models.CharField(max_length=64)),
                ('genesis_live_account', models.CharField(max_length=65)),
                ('genesis_live_work', models.CharField(max_length=16)),
                ('genesis_live_signature', models.CharField(max_length=128)),
                ('genesis_test_public_key', models.CharField(max_length=64)),
                ('genesis_test_account', models.CharField(max_length=65)),
                ('genesis_test_work', models.CharField(max_length=16)),
                ('genesis_test_signature', models.CharField(max_length=128)),
                ('beta_pre_conf_rep_public_key_0', models.CharField(max_length=64)),
                ('beta_pre_conf_rep_public_key_1', models.CharField(max_length=64)),
                ('beta_pre_conf_rep_private_key_0', models.CharField(max_length=64)),
                ('beta_pre_conf_rep_private_key_1', models.CharField(max_length=64)),
                ('live_pre_conf_rep_public_key_0', models.CharField(max_length=64)),
                ('live_pre_conf_rep_public_key_1', models.CharField(max_length=64)),
                ('live_pre_conf_rep_public_key_2', models.CharField(max_length=64)),
                ('live_pre_conf_rep_public_key_3', models.CharField(max_length=64)),
                ('live_pre_conf_rep_public_key_4', models.CharField(max_length=64)),
                ('live_pre_conf_rep_public_key_5', models.CharField(max_length=64)),
                ('live_pre_conf_rep_public_key_6', models.CharField(max_length=64)),
                ('live_pre_conf_rep_public_key_7', models.CharField(max_length=64)),
                ('live_pre_conf_rep_private_key_0', models.CharField(max_length=64)),
                ('live_pre_conf_rep_private_key_1', models.CharField(max_length=64)),
                ('live_pre_conf_rep_private_key_2', models.CharField(max_length=64)),
                ('live_pre_conf_rep_private_key_3', models.CharField(max_length=64)),
                ('live_pre_conf_rep_private_key_4', models.CharField(max_length=64)),
                ('live_pre_conf_rep_private_key_5', models.CharField(max_length=64)),
                ('live_pre_conf_rep_private_key_6', models.CharField(max_length=64)),
                ('live_pre_conf_rep_private_key_7', models.CharField(max_length=64)),
                ('live_node_peering_port', models.CharField(max_length=5)),
                ('beta_node_peering_port', models.CharField(max_length=5)),
                ('test_node_peering_port', models.CharField(max_length=5)),
                ('live_rpc_port', models.CharField(max_length=5)),
                ('beta_rpc_port', models.CharField(max_length=5)),
                ('test_rpc_port', models.CharField(max_length=5)),
                ('logging', models.CharField(blank=True, default='INFO', max_length=100)),
                ('node_version', models.CharField(max_length=100)),
                ('binary_public', models.BooleanField(default=False)),
                ('s3_bucket_name', models.CharField(blank=True, max_length=256)),
                ('number_of_peers', models.IntegerField(default=2)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
    ]
