# Generated by Django 3.2.8 on 2021-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainbuilddeploy',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Build'), (2, 'Deploy'), (3, 'Terminate')], default=1),
        ),
    ]
