# Generated by Django 3.2.8 on 2021-11-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockchain',
            options={'ordering': ['id']},
        ),
    ]
