# Generated by Django 3.2.8 on 2022-01-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='nault_price_url',
            field=models.CharField(default='https://api.coingecko.com/api/v3/coins/nano?localization=false&tickers=false&market_data=true', max_length=1024),
        ),
        migrations.AddField(
            model_name='blockchain',
            name='proxy_price_url',
            field=models.CharField(default='https://api.coinpaprika.com/v1/tickers/nano-nano', max_length=1024),
        ),
    ]
