# Generated by Django 3.2.8 on 2021-11-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='nano_network',
            field=models.CharField(default='live', max_length=64),
        ),
    ]
