# Generated by Django 3.2.8 on 2021-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='ninja_version',
            field=models.CharField(default='663a5b24e2a8e1d423fc3311a6945cc0d234953e', max_length=64),
        ),
    ]
