# Generated by Django 3.2.8 on 2021-11-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blockchain_nano_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Created'), (2, 'Deploying'), (3, 'Deployed'), (4, 'Pending'), (4, 'Suspended'), (5, 'Error')], default=1),
        ),
    ]
