# Generated by Django 3.2.8 on 2021-11-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_organization_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockchain',
            old_name='created',
            new_name='created_at',
        ),
    ]
