# Generated by Django 3.2.8 on 2021-11-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blockchain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='nault_version',
            field=models.CharField(default='v1.15.0', max_length=64),
        ),
    ]
