# Generated by Django 3.2.8 on 2022-01-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_blockchain_work_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='supply_multiplier',
            field=models.PositiveIntegerField(choices=[(1, '1000000000000000000000000000000'), (2, '10000000000000000000000000000000'), (3, '100000000000000000000000000000000'), (4, '1000000000000000000000000000000000')], default=1),
        ),
    ]
