# Generated by Django 3.2.8 on 2021-11-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockchain_nault_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchainbuilddeploy',
            name='block_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_chain', to='api.blockchain'),
        ),
    ]
