# Generated by Django 3.2.8 on 2022-01-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blockchain_supply_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='supply_multiplier',
            field=models.PositiveIntegerField(choices=[(1, '1000000000000000000000000000000'), (2, '100000000000000000000000000000'), (3, '10000000000000000000000000000'), (4, '1000000000000000000000000000')], default=1),
        ),
    ]
