# Generated by Django 3.2.8 on 2021-12-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211201_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainbuilddeploy',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
