# Generated by Django 3.2.8 on 2021-11-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_blockchainbuilddeploy_block_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainbuilddeploy',
            name='status',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
