# Generated by Django 3.2.8 on 2022-01-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blockchain_supply_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='supply_multiplier',
            field=models.CharField(choices=[('1000000000000000000000000000000', '1000000000000000000000000000000'), ('100000000000000000000000000000', '100000000000000000000000000000'), ('10000000000000000000000000000', '10000000000000000000000000000'), ('1000000000000000000000000000', '1000000000000000000000000000')], default='100000000000000000000000000000', max_length=128),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='work_threshold',
            field=models.CharField(choices=[('fffffe0000000000,fffffff000000000,0000000000000000', 'BANANO'), ('ffffffc000000000,fffffff800000000,fffffe0000000000', 'NANO')], default='ffffffc000000000,fffffff800000000,fffffe0000000000', max_length=128),
        ),
    ]
