# Generated by Django 3.2.8 on 2021-11-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blockchainbuilddeploy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainbuilddeploy',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Build'), (2, 'Deploy')], default=1),
        ),
    ]
