# Generated by Django 3.2.8 on 2022-01-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220121_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain',
            name='supply_multiplier',
            field=models.CharField(choices=[('1000000000000000000000000000000', 'MILLIONs'), ('100000000000000000000000000000', 'BILLIONs'), ('10000000000000000000000000000', 'TEN_BILLIONs'), ('1000000000000000000000000000', 'HUNDRED_BILLIONs')], default='100000000000000000000000000000', max_length=128),
        ),
    ]
