# Generated by Django 3.2.8 on 2021-11-23 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_blockchainbuilddeploy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainbuilddeploy',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blockchainbuilddeploy',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='block_chain_build_deploy_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
