# Generated by Django 3.2.8 on 2022-01-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blockchain_supply_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='nault_store_key',
            field=models.CharField(blank=True, default='None', max_length=128),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='nault_price_url',
            field=models.CharField(default='None', max_length=1024),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='proxy_price_url',
            field=models.CharField(default='None', max_length=1024),
        ),
    ]
