# Generated by Django 3.2.8 on 2021-11-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_blockchainbuilddeploy_parent_build_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainbuilddeploy',
            name='parent_build_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blockchainbuilddeploy',
            name='parent_build_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
