# Generated by Django 3.2.8 on 2022-02-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220121_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='nault_hid_rep_help',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='abbreviation',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
