# Generated by Django 3.2.8 on 2022-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220202_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='k8s_cluster',
            field=models.CharField(default='k8s0', max_length=64),
        ),
    ]
