# Generated by Django 3.2.8 on 2022-02-21 18:41

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blockchain_k8s_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneCIServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='', max_length=2048)),
                ('server', models.URLField(blank=True, default='', max_length=254)),
                ('token', encrypted_model_fields.fields.EncryptedCharField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='blockchainbuilddeploy',
            name='droneci_server',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='droneci_server', to='api.droneciserver'),
        ),
    ]
